//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taller_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosClientes
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Dirección { get; set; }
        public Nullable<long> NumeroDeTelefono { get; set; }
        public string Vehículo { get; set; }
        public string Patente { get; set; }
        public string NumeroChasis { get; set; }
        public Nullable<long> Kilómetros { get; set; }
        public string FechaDeMantenimiento { get; set; }
        public string FechaProximoMant { get; set; }
        public string Descripción { get; set; }
    }
}
